### ISSUE TITLE
Problem with kotlin 1.4.30

### ISSUE THREAD

**Issue by uberchilly** [cashapp/contour#121]
java.lang.NoSuchMethodError: No virtual method getYdip-dBGyhoQ(I)I in class

Tried with contour 1.1.0-SNAPSHOT as well, same error. 

When I downgrade kotlin to 1.4.20 everything works.

**Comment by saket** [comment]
Can you try out `1.1.0-SNAPSHOT` again and check if this is fixed? Feel free to reopen if it's not.

**Comment by uberchilly** [comment]
It looks like everything is working with 1.1.0-SNAPSHOT
